### ISSUE TITLE
Class 'TestHelpers' has no dependencies or dependents

### ISSUE THREAD

**Issue by Phlip** [dlew/android-shared-test-module-example#1]
my project does not revolve around Gradle configuration, so I don't know what to do when Android-Studio's code inspector reports this warning.

My library-shared-test/build.gradle file looks like this. The build works correctly and shares my TestHelper class between my unit tests and Android tests (thanks!):

----

plugins {
    id 'com.android.library'
}

android {
    compileSdk 30

    defaultConfig {
        minSdk 28
        targetSdk 30
    }
}

dependencies {
    implementation project(':app')
    implementation 'org.jetbrains:annotations:15.0'
    implementation 'junit:junit:4.13.2'
    implementation 'androidx.appcompat:appcompat:1.3.1'
}

**Comment by dlew** [comment]
>  The build works correctly and shares my TestHelper class between my unit tests and Android tests

I'm not sure what you're asking for here, especially since you say that everything works correctly.

Regardless, this is an issue tracker for problems with the sample, not StackOverflow. If you have trouble with your build, please try StackOverflow (or similar) instead.
